Numpy Array.
In this lesson we will go over numpy array creation.


Creating one dimensional arrays

In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5])

In [5]:
print(x)

[1 2 3 4 5]


In [6]:
print(type(x))

<class 'numpy.ndarray'>


Use dtype to check the type of the elements in the arrays


In [7]:
x.dtype


dtype('int64')

Use shape to determine the shape of the array


In [8]:
x.shape

(5,)

In [13]:
y = np.array([[1,2,3,], [4,5,6], [7,8,-1], [10,11,10]])

In [14]:
print(y)
print(y.min(axis=0))
print(y.min(axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 -1]
 [10 11 10]]
[ 1  2 -1]
[ 1  4 -1 10]


In [13]:
y.shape

(4, 3)

In [14]:
y.size

12

You can specify the data type of a Numpy array as follows:

In [15]:
s = np.array([1,2,4,3], dtype=np.int64)
print(s)
print('dtype: ', x.dtype)

[1 2 4 3]
dtype:  int64


To Save an NP arrayto the current dir, use the save function

In [16]:
np.save('my_s_np_array', s)

To Load the saved NP array into a variable, use the load function. Note that the load Function requires the .npy extention at the end of the file name.

In [19]:
l = np.load('my_s_np_array.npy')
print(l)

[1 2 4 3]


### Using Build in functions

Creating Numpy Arrays using Buildin Functions


We can generate np array to generate numpy arrays.


Numpy Zeros function.

In [20]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Numpy Ones function


In [22]:
X = np.ones((3,4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
X = np.ones((3,4), dtype=int)
print(X)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


To create an array full of a single value, use the Full function.
It takes the shape of the array and a value you want the array to have. 

In [24]:
f = np.full((5,5), 5)
print(f)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


To create an Identity Matrix, use the eye function. Recall that the identity matrix is a square matrix with ones in the diagonal.


In [25]:
y = np.eye(5)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


We can use Numpy Diag function to create a diagonal matrix with specific values in the diagonal

In [26]:
d = np.diag([10,20,30,40])
print(d)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


To create arrays with evenly spaced out numbers, we can use arange function. The function takes in three arguments(start, stop, step).
If only one argument is passed, arange will create a matrix with items up to that value - 1. This is because np.array are zero based arrays.


In [27]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [29]:
a = np.arange(10,100,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


The output of arange is inconsistent due to finite floating point numbers. When we need precise non integer steps, we can use the linspace function instead.
The linspace function takes in three arguments: start, stop, end. 
This function returns end evenly spaced array from start to stop. 

Unlike arange, linspace requires two arguments: start, stop. If stop is no specified, it defaults to 50

Start and end are inclusive by default. You can set the endpoint to be exclusive by using the endpoint=False an argument.

In [31]:
l = np.linspace(0,10)
print(l)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [32]:
l = np.linspace(0,10,3)
print(l)

[ 0.  5. 10.]


In [33]:
l = np.linspace(0,10,3, endpoint=False)
print(l)

[0.         3.33333333 6.66666667]


The Reshape function allows you to take a n dimensional array and reshape it accordingly. For instance, we can use the output of a arange or linspace array and reshape it. Note that new shape dimension must conform with the number of elements on the original array.

For instance, a one dimensional array with 20 elements can be reshape into a (4,5) two dimensional array.


In [35]:
a = np.arange(20)
r = np.reshape(a, (4,5))
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [36]:
rs = np.reshape(a, (10,2))
print(rs)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


We can use numpy . notation to get the same result above.

In [39]:
rdot = np.arange(20).reshape((10,2))
print(rdot)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [41]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5,2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


Creating Random Number Arrays