Deleting elements in a NP Array

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])

In [3]:
X = np.delete(x, [0,3])
print(X)


[2 3]


Deleting elements in a 2 dimensional array

In [6]:
s = np.arange(1,10).reshape(3,3)

In [7]:
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
w = np.delete(s, 0, axis = 0)
print(w)

[[4 5 6]
 [7 8 9]]


To delete the first and last column in S

In [9]:
v = np.delete(s, [0,2], axis=1)
print(v)

[[2]
 [5]
 [8]]


Appending Elements to a NP Array

In [17]:
a = np.eye(5, dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [18]:
a = np.append(a, [[1,2,3,4,5]], axis=0)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [1 2 3 4 5]]


Appending a columnt to a

In [20]:
a = np.append(a, [[6], [7], [8],[9],[10],[11]], axis=1)
print(a)

[[ 1  0  0  0  0  6]
 [ 0  1  0  0  0  7]
 [ 0  0  1  0  0  8]
 [ 0  0  0  1  0  9]
 [ 0  0  0  0  1 10]
 [ 1  2  3  4  5 11]]
