Numpy Array.
In this lesson we will go over numpy array creation.


Creating one dimensional arrays

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
print(x)

[1 2 3 4 5]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


Use dtype to check the type of the elements in the arrays


In [7]:
x.dtype


dtype('int64')

Use shape to determine the shape of the array


In [8]:
x.shape

(5,)

In [11]:
y = np.array([[1,2,3,], [4,5,6], [7,8,9], [10,11,10]])

In [12]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 10]]


In [13]:
y.shape

(4, 3)

In [14]:
y.size

12

You can specify the data type of a Numpy array as follows:

In [15]:
s = np.array([1,2,4,3], dtype=np.int64)
print(s)
print('dtype: ', x.dtype)

[1 2 4 3]
dtype:  int64


To Save an NP arrayto the current dir, use the save function

In [16]:
np.save('my_s_np_array', s)

To Load the saved NP array into a variable, use the load function

In [18]:
l = np.load('my_s_np_array)
print(l)

SyntaxError: EOL while scanning string literal (<ipython-input-18-14a3756bfd81>, line 1)